<%@ Page Title="" Language="C#" MasterPageFile="~/Manage.master" AutoEventWireup="true" CodeFile="rechargedata.aspx.cs" Inherits="rechargedata" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
    <html>
<body>
<center>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="<%$ ConnectionStrings:RegiConnectionString %>" 
        SelectCommand="SELECT * FROM [Recharge]"
        updateCommand="UPDATE [Recharge] Set [Amount]=@amu, [Talktime]=@talk, [Validity]=@vali, [Description]=@dis Where [Id]=@id" DeleteCommand="DELETE FROM Recharge">
        </asp:SqlDataSource>
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
        CellPadding="4" DataSourceID="SqlDataSource1" ForeColor="#333333" 
        GridLines="None" Width="269px" AutoGenerateDeleteButton="True">
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:CommandField ShowSelectButton="True" />
            <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" />
            <asp:BoundField DataField="Amount" HeaderText="Amount" 
                SortExpression="Amount" />
            <asp:BoundField DataField="Talktime" HeaderText="Talktime" 
                SortExpression="Talktime" />
            <asp:BoundField DataField="Validity" HeaderText="Validity" 
                SortExpression="Validity" />
            <asp:BoundField DataField="Description" HeaderText="Description" 
                SortExpression="Description" />
        </Columns>
        <EditRowStyle BackColor="#2461BF" />
        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#EFF3FB" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#F5F7FB" />
        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
        <SortedDescendingCellStyle BackColor="#E9EBEF" />
        <SortedDescendingHeaderStyle BackColor="#4870BE" />
    </asp:GridView>
    <br />
   <div style="font-size: x-large; font-weight: 700; font-style: italic; color: #FFFFFF; background-color: #0099FF">Insert Recharge Details</div>
    <table>
    <tr>
   <td>Id:</td> <td>
        <asp:DropDownList ID="ddlrechid" runat="server" 
            onselectedindexchanged="DropDownList1_SelectedIndexChanged">
            <asp:ListItem Selected="True">select id</asp:ListItem>
            <asp:ListItem>1</asp:ListItem>
            <asp:ListItem>2</asp:ListItem>
            <asp:ListItem>3</asp:ListItem>
            <asp:ListItem>4</asp:ListItem>
            <asp:ListItem>5</asp:ListItem>
            <asp:ListItem>6</asp:ListItem>
            <asp:ListItem>7</asp:ListItem>
            <asp:ListItem>8</asp:ListItem>
            <asp:ListItem>9</asp:ListItem>
            <asp:ListItem>10</asp:ListItem>
        </asp:DropDownList>
      
        <asp:Label ID="lblcheckid" runat="server" Text="" 
            style="font-weight: 700; font-style: italic; background-color: #FF0000"></asp:Label>
      
        </td><td> 
            <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" 
                ControlToValidate="ddlrechid" ErrorMessage="Select Id" 
                style="font-weight: bold; font-style: italic; color: #FF0000" 
                InitialValue="select id"></asp:RequiredFieldValidator>
        </td>
    </tr>
    <tr>
    <td>Amount:</td><td> 
        <asp:TextBox ID="txtamu" runat="server"></asp:TextBox></td><td>  
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                ControlToValidate="txtamu" ErrorMessage="Enter Amount" 
                style="font-weight: bold; font-style: italic; color: #FF0000"></asp:RequiredFieldValidator>
        </td></tr>
        <tr>
    <td>Talktime</td><td>
        <asp:TextBox ID="txttalk" runat="server"></asp:TextBox></td><td>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" 
                    ControlToValidate="txttalk" ErrorMessage="Enter the Amount" 
                    style="font-weight: bold; font-style: italic; color: #FF0000"></asp:RequiredFieldValidator>
            </td></tr>
        <tr>
    <td>Validity</td><td>
        <asp:TextBox ID="txtvali" runat="server"></asp:TextBox></td><td>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" 
                    ControlToValidate="txtvali" ErrorMessage="Enter the Validity" 
                    style="font-weight: bold; font-style: italic; color: #FF0000"></asp:RequiredFieldValidator>
            </td></tr>
        <tr>
    <td>Description:</td><td>
        <asp:TextBox ID="txtdis" runat="server"></asp:TextBox></td><td>
                <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" 
                    ControlToValidate="txtdis" ErrorMessage="Enter the Description" 
                    style="font-weight: bold; font-style: italic; color: #FF0000"></asp:RequiredFieldValidator>
            </td>

    </tr>
    <tr>
    <td></td><td>
        <asp:Button ID="btninsert" runat="server" Text="Insert" 
            onclick="btninsert_Click" style="height: 26px" /></td>
    </tr>
    </table>
    </center>
</body>
</html>
</asp:Content>

